---
title: "Hotel Cancellations"
output: html_document
---

```{r}
rm(list=ls())

library(dplyr)
library(tidymodels)
library(ggplot2)
library(ggeasy)


data <- read.csv("hotel_bookings.csv")
head(data)



```
# EDA

```{r}
# Interesting note about patrons, supposedly 403 of the observations have no adults registered and 32 of those observations no adult, children, or babies
data %>%
  group_by(adults) %>%
  count()
test_adults <- data %>%
  filter(adults == 0, children == 0, babies == 0)



#Cancellations by type of Hotel
hotel_cancel <-  data %>%
  group_by(hotel) %>%
  summarise(Cancelation_Rate = round(mean(is_canceled)*100,2)) 
hotel_cancel

Cancelation_by_hotel_type <- ggplot(data = hotel_cancel, aes(x = hotel, y = Cancelation_Rate, label = Cancelation_Rate)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  geom_text(size = 5, position = position_stack(vjust = 0.5)) +
  xlab("Type of Hotel") +
  ylab("Cancelation Rate (%)") +
  ggtitle("Cancelation Rate by Hotel Type") +
  theme_classic()+
  ggeasy::easy_center_title()


Cancelation_by_hotel_type


# Cancellations with children/babies
# created a column if the people had children
# Had to omit NA's as there was 32 observations
family_cancel <- data %>%
  mutate(has_children = if_else(children > 0 | babies > 0, 1, 0)) %>%
  na.omit()

#data is heavily skewed away from children

family_cancel %>%
  group_by(hotel) %>%
  summarise(freq = round(mean(has_children)*100,2))

family_cancel_1 <- family_cancel %>%
  filter(has_children > 0) %>%
  group_by(hotel) %>%
  summarise(Cancelation_Rate = round(mean(is_canceled)*100,1))

family_cancel_1


Cancelation_by_children <- ggplot(data = family_cancel_1, aes(x = hotel, y = Cancelation_Rate, label = Cancelation_Rate)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  geom_text(size = 5, position = position_stack(vjust = 0.5)) +
  xlab("Type of Hotel") +
  ylab("Cancelation Rate (%)") +
  ggtitle("Cancelation Rate by Hotel Type with Children") +
  theme_classic()+
  ggeasy::easy_center_title()

Cancelation_by_children


# Cancellations by lead time, With both types of hotels. Not much difference in the distributions when both types are separated
cancel_lead_time <- data %>%
  filter(lead_time <= 365) %>%
  group_by(lead_time) %>% 
  summarise(Cancellation_rate = round(mean(is_canceled)*100,1))

cancel_lead_time

cancel_by_lead_time <- ggplot(data = cancel_lead_time, aes(x = lead_time, y = Cancellation_rate)) +
  geom_point() +
  scale_x_continuous(breaks = c( 14,30,60, 90, 120, 180, 240, 365)) +
  xlab("Lead Time") +
  ylab("Cancelation Rate (%)") +
  ggtitle("Cancelation Rate Based on Lead Time") +
  theme_classic()+
  ggeasy::easy_center_title()
  
                              
cancel_by_lead_time


# Percent canceled by region
region_canceled <- data %>%
  group_by(country) %>%
  summarise(Cancelelation_Rate = round(mean(is_canceled)*100,2))

region_canceled


# Distribution channel based on hotel type
city_distribution <- data %>%
  filter(hotel == "City Hotel", is_canceled == 1) %>%
  group_by(distribution_channel) %>%
  count()

city_distribution

city_distribution_cancel <- ggplot(data = city_distribution, aes(x = reorder( distribution_channel, -n), y = n)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  xlab("Distribution Channel") +
  ylab("Total Cancellations") +
  ggtitle("Total City Cancelations Based on Distribution Channel") +
  theme_classic()+
  ggeasy::easy_center_title()

city_distribution_cancel


#Resort Hotel Distribution Cancellations
resort_distribution <- data %>%
  filter(hotel == "Resort Hotel", is_canceled == 1) %>%
  group_by(distribution_channel) %>%
  count()

resort_distribution


resort_distribution_cancel <- ggplot(data = resort_distribution, aes(x = reorder( distribution_channel, -n), y = n)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  xlab("Distribution Channel") +
  ylab("Total Cancellations") +
  ggtitle("Total Resort Cancelations Based on Distribution Channel") +
  theme_classic()+
  ggeasy::easy_center_title()

resort_distribution_cancel



#portion of bookings by distribution channel
portion_distribution_city <- data %>%
  filter(hotel == "City") %>% 
  group_by()

```



